version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000"
    environment:
      - APP_ENV=dev
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - "27017:27017"
